name: codecov
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm ci
      - name: Run tests with coverage
        run: npm run coverage
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
        if: always()